shared:
    image: node:6
    settings:
        email:
            addresses:
                - thejerryzhang@gmail.com
                - jerryzhang222@yahoo.com
            statuses:
                - SUCCESS
                - FAILURE
jobs:
    main:
        steps:
            - save: echo hello > $SD_ARTIFACTS_DIR/hello.txt
